# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]

viaIR = true
ffi = true
evm_version = "shanghai"
fs_permissions = [
    { access='read', path='./deploy-config/' },
    { access='read-write', path='./deployments/' }
]
